name: format-check

on:
  pull_request:
    branches:
      - main

env: # environment variables
  julia_version: '1.8.2'

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ env.julia_version }}

      - uses: actions/checkout@main
      
      - name: Install JuliaFormatter
        run: julia  -e 'using Pkg; Pkg.add("JuliaFormatter")'
      
      - name: Run JuliaFormatter
        run: julia  -e 'using JuliaFormatter; format(".", verbose=true)'
          
      - name: Formatting Check
        run: |
          julia -e '
          out = Cmd(`git diff --name-only`) |> read |> String
          if out == ""
              exit(0)
          else
              @error "Some files have not been formatted !!!"
              write(stdout, out)
              exit(1)
          end'

      - if: ${{ failure() }}
        id: juliaformatter-pr
        name: Formatting PR
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: JuliaFormatter Action Bot
          title: 'Automatic JuliaFormatter.jl run'
          branch: auto-juliaformatter-pr
          delete-branch: true
          labels: formatting, automated pr, no changelog

      - name: PR Info
        run: |
          echo "Pull Request Number - ${{ steps.juliaformatter-pr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.juliaformatter-pr.outputs.pull-request-url }}"
